### ISSUE TITLE
Testing might not work for UserController/JobController with current file I/O methods

### ISSUE THREAD

**Issue by ddh** [HuSCII/HuSCII#40]
I ran into an issue when making JUnit tests; 

```
    java.lang.NullPointerException
at java.io.Reader.<init>(Unknown Source)
at java.io.InputStreamReader.<init>(Unknown Source)
at java.util.Scanner.<init>(Unknown Source)
at models.UserController.readUserFile(UserController.java:51)
at models.UserController.<init>(UserController.java:40)
at tests.UserControllerTest.setUp(UserControllerTest.java:36)
```

Culprit might be how we're reading in files:

```
    final InputStream in = this.getClass().getResourceAsStream(inputFile);
```

the getClass() might be breaking my tests...perhaps.

**Comment by ianmcpeek** [comment]
could be the jobFile too. Now they require us to read in 2 dates for job
duration but currently the file hasn't implemented that. But not sure if
userController uses the jobFile at all.
